# Use a minimal base image for the final container
FROM alpine:latest

# Set the working directory
WORKDIR /app

# Define default environment variables for port.
# These can be overridden when running the container (e.g., using `docker run -e ...`)
ENV APP_PORT="8080"

# Copy the built binary from the builder stage
COPY jobbtid /app/jobbtid

# Expose the port the application will listen on.
# This informs Docker that the container listens on this network port.
EXPOSE $APP_PORT

# Command to run the application when the container starts
# Executes the binary located at /app/jobbtid
ENTRYPOINT ["./app/jobbtid"]
